/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bmzmoukpjtuzffxwkkqs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtem1vdWtwanR1emZmeHdra3FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxODc2MjIsImV4cCI6MjA4NTc2MzYyMn0.sCRahoZ9B-Zl_Z3lVuB5GewwvyRj17t0fEM3pkZmh_U"
